### ISSUE TITLE
Transfer share link password

### ISSUE THREAD

**Issue by IljaN** [owncloud/data_exporter#10]
When a new link share is created with a password, that password is hashed always. This prevents the old password from being used in the new server because the hashed password we're transfering will always be rehashed.

Expected core changes are in https://github.com/owncloud/core/issues/32383

This means importing would only work correctly in OC 10.0.10.

- [ ] We might need to protect against missing API in case we import in OC < 10. Maybe display a warning that "link share passwords" will not be importable in this version. In this case should we generate a random password instead of setting the hash and let it be hashed ?

- [ ] document limitation (no share link password import in OC < 10.0.10)

**Comment by micbar** [comment]
Closed by #58
