### ISSUE TITLE
data_exporter 0.2.1 - Error when exporting with empty trash bin

### ISSUE THREAD

**Issue by GeraldLeikam** [owncloud/data_exporter#209]
If the trash bin is empty when exporting, an error will be issued. However, the export works without any problems even with this error. The error does not appear if there is at least 1 file in the trash bin or files have already been in the trash bin.

![Screenshot from 2022-08-16 12-52-11](https://user-images.githubusercontent.com/54261654/184862565-309dee2f-57e4-4e9b-aa28-24d8862511bb.png)

This is not a blocking issue!

**Comment by jnweiger** [comment]
Confirmed fixed in data_exporter-0.2.2
