### ISSUE TITLE
data_exporter 0.2.1 - Error when importing with empty trash bin

### ISSUE THREAD

**Issue by GeraldLeikam** [owncloud/data_exporter#210]
If a user is imported with an empty trash bin, an error will be thrown during the import. However, this does not affect the functionality of the import and is therefore not a blocker

![Screenshot from 2022-08-16 13-03-59](https://user-images.githubusercontent.com/54261654/184864561-34dd5343-3969-43e5-9aa8-79f61615e514.png)
.

**Comment by phil-davis** [comment]
Should be fixed by #229
