### ISSUE TITLE
Add test coverage for restoring with an empty trashbin

### ISSUE THREAD

**Issue by phil-davis** [owncloud/data_exporter#211]
Add acceptance test coverage for the situation in issues #209 and #210

Maybe: To get an export that has an empty trashbin, it might be necessary for the test scenario to create a user, upload a file(s), delete a file (trashbin will now exist) and then delete the file from the trashbin (trashbin will now exist and be empty). Then export the user and try to import them.

**Comment by SwikritiT** [comment]
@nabim777 will be working on this

**Comment by SagarGi** [comment]
All the PR's has been merged to cover tests. So Closing this issue.
