### ISSUE TITLE
Release data_exporter 0.3.0

### ISSUE THREAD

**Issue by phil-davis** [owncloud/data_exporter#223]
### Reasons

- Needed to go with server core 10.13 because of the Symfony 4 to 5 upgrade https://github.com/owncloud/core/issues/39630
- PR #222 made code changes needed for Symfony 5

Note: the change in that PR also works fine with server core 10.12 - min-version has been bumped to 10.12

The app can be released any time before 10.13 - it should work fine with 10.12

**Comment by phil-davis** [comment]
Also, issue #209 was fixed by PR #227

**Comment by phil-davis** [comment]
Note: there is discussion in PR #222 about if we actually wan to, or have to, upgrade the app code to Symfony5. So a release because of that may not be essential.

**Comment by jnweiger** [comment]
## Issues seen while testing
* [ ] https://github.com/owncloud/data_exporter/issues/230

**Comment by jnweiger** [comment]
https://github.com/owncloud/data_exporter/releases/download/v0.3.0-rc.1/data_exporter-0.3.0-rc.1.tar.gz

**Comment by jnweiger** [comment]
#222 is included in
https://github.com/owncloud/data_exporter/releases/download/v0.3.0-rc.3/data_exporter-0.3.0-rc.3.tar.gz

**Comment by pako81** [comment]
https://github.com/owncloud/data_exporter/releases/tag/v0.2.2 changelog does not seem correct as there is apparently no php `min-version` enforcement in version 0.2.2.

**Comment by jnweiger** [comment]
> https://github.com/owncloud/data_exporter/releases/tag/v0.2.2 changelog does not seem completely correct as there is apparently no php `min-version` enforcement in version 0.2.2.

thanks, rebuilt with a fixed CHANGELOG

**Comment by jnweiger** [comment]
Github only release done.
