### ISSUE TITLE
Don't read whole file in to memory on importing/exporting

### ISSUE THREAD

**Issue by IljaN** [owncloud/data_exporter#28]
https://github.com/owncloud/data_exporter/blob/master/lib/Importer/FilesImporter.php#L67
https://github.com/owncloud/data_exporter/blob/master/lib/Exporter/FilesExporter.php#L63

**Comment by PVince81** [comment]
estimate ?

**Comment by IljaN** [comment]
Already done, was ~1h, tests will be provided trough #29

**Comment by jvillafanez** [comment]
This is done as part of https://github.com/owncloud/data_exporter/pull/39. Note that the metadata.json file still needs to be read / written as a whole due to limitations in the serializer.

**Comment by micbar** [comment]
Fixed by #89
