### ISSUE TITLE
Refactor Node Iterator

### ISSUE THREAD

**Issue by IljaN** [owncloud/data_exporter#29]
Currently a filter Iterator is used which as the name implies just filters the nodes which needs to be iterated but internally still iterates everything. This results in that for example ext. storages are also iterated.

https://github.com/owncloud/data_exporter/blob/9bf601794cdc1226a02533705de75a4a677311bf/lib/Exporter/UserStorageIterator.php#L70

Merge UserStorageIterator and RecursiveNodeIterator and manually implement skiping rules instead of using php filter behaviour.

**Comment by PVince81** [comment]
estimate ?

**Comment by IljaN** [comment]
I used ~0.5 md already. Now 0.5 md left for tests.

**Comment by IljaN** [comment]
Estimate was around 1h tests will be provided trough #29

**Comment by IljaN** [comment]
Solved via #33
