### ISSUE TITLE
Data Exporter 0.1.1

### ISSUE THREAD

**Issue by PVince81** [owncloud/data_exporter#63]
### Reason
- For https://github.com/owncloud/data_exporter/pull/58#issuecomment-457598547
- [x] check for more change / changelog => no other items found

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch with the format "release-$version"
- [ ] Create "$version Testplan"

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & github only release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)
- ~~Create github tag for 'v${version}RC1'~~
- ~~Build and sign RC tarball from github tag 'v${version}RC1' with `make dist` and upload as Github release~~
- ~~Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing~~
- [ ] Create github tag for final 'v${version}'
- [ ] Build and sign final tarball from github tag 'v${version}' with `make dist` and upload as Github release
- [ ] Smoke test tarball (at least install + enable)
- ~~Upload to marketplace~~
- ~~Publish for customers~~
- [ ] Send mail to release-coordination with link to this ticket and to the changelog
- [ ] Rename QA milestone to '$version'
- [ ] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [ ] Create PR to merge changes back to the `master` branch

**Comment by PVince81** [comment]
- [ ] missing signing key?

**Comment by PVince81** [comment]
- 0.1.1RC1 here: https://github.com/owncloud/data_exporter/releases/tag/v0.1.1RC1

not signed yet, will sort this out for final build

@cdamken please test the above

**Comment by mmattel** [comment]
Proposal, as this app progresses, add an icon/picture for it.
Starting this now would ease life to avoid later rush and improves professionality...

@hurradieweltgehtunter fyi

**Comment by PVince81** [comment]
raised here for icon and picture for later: https://github.com/owncloud/data_exporter/issues/64

**Comment by hurradieweltgehtunter** [comment]
@mmattel working on image and icon, ETA: mid February as timed with @PVince81

**Comment by patrickjahns** [comment]
@micbar @IljaN 
Can you help to decide if we push forwards this release or if we wait for your changes

**Comment by IljaN** [comment]
Will create new issue for next release which will break and change everything.
