### ISSUE TITLE
Icon and picture

### ISSUE THREAD

**Issue by PVince81** [owncloud/data_exporter#64]
@hurradieweltgehtunter @mmattel

**Comment by hurradieweltgehtunter** [comment]
both are worked on. ETA: mid Feb

**Comment by hurradieweltgehtunter** [comment]
Image is ready and uploaded: https://github.com/owncloud/screenshots/tree/master/data_exporter
Feedback for changes are welcome.
@mmattel @PVince81 @pmaier1 

Icon will follow.

![owncloud-app-data-exporter](https://user-images.githubusercontent.com/16665512/52558003-61a3be00-2df1-11e9-90b1-942f76f3a25d.jpg)

**Comment by hurradieweltgehtunter** [comment]
Icon is also ready and uploaded: https://github.com/owncloud/screenshots/blob/master/data_exporter/owncloud-app-data-exporter_icon_50x50.jpg

![owncloud-app-data-exporter_icon_50x50](https://user-images.githubusercontent.com/16665512/53001791-c384a900-342b-11e9-8d3c-2de560600f0d.jpg)

**Comment by micbar** [comment]
Closed by #66
